%YAML:1.0


Scale_factor: 20 
Tcw_form: 0
Cloud_max_x: 30
Cloud_min_x: -10
Cloud_max_z: 20
Cloud_min_z: -20
Free_thresh: 0.6
Occupied_thresh: 0.5
Use_local_counters: 1
Use_gaussian_counters: 1
Use_boundary_detection: 1
Publish_trajectory: 0
Visit_thresh: 5
Thresh_extension: 0
Step_extension: 10
Gaussian_kernel_size: 3
Canny_thresh: 350
Upper_height: 1
Lower_heught: -1
Make_submaps: 1
Use_semantic_filter: 0